-- ============================================================
-- ActivoPOS — Seed FAQs únicas por segmento
-- 9 segmentos × 12 FAQs = 108 registros
-- FAQs 1-3: específicas del giro (UPDATE de las existentes)
-- FAQs 4-12: comunes pero con respuesta única por giro
-- CLI-A ejecuta: mysql activopos < seed_faqs_segmentos.sql
-- ============================================================

-- Limpiar FAQs existentes para reinsertar limpias
DELETE FROM segment_faqs WHERE segment_id IN (
  'cmr9tor2a0003rcvxjtqaq5v4',
  'cmr9tor2t0007rcvxz6j0lhw8',
  'cmr9tor3b000brcvx7b7hkrk9',
  'cmr9tor3s000frcvxz4vivpgp',
  'cmr9tor6v000jrcvxw875298h',
  'cmr9tor78000nrcvx4nvtcglc',
  'cmr9tor7s000rrcvxk633xs8c',
  'cmr9tor86000vrcvxcznm1opt',
  'cmr9tor8q0013rcvx66mexwzw'
);

-- ============================================================
-- CARNICERÍA
-- ============================================================
INSERT INTO segment_faqs (id, segment_id, question, answer, sort_order) VALUES
('faq_car_01', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Puedo vender por kilo y por pieza en el mismo sistema?',
'Sí. ActivoPOS maneja unidades de medida por producto — configuras res, cerdo y pollo por kilo, y las morcillas o chorizos por pieza. El sistema calcula el precio automáticamente según el peso o la unidad que ingreses en cada venta.',
1),
('faq_car_02', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Cómo maneja ActivoPOS la tasa del dólar en la carnicería?',
'La tasa BCV se actualiza automáticamente varias veces al día. Tú defines el precio de cada corte en dólares una sola vez — el sistema convierte a bolívares en tiempo real en cada cobro. Cuando el dólar sube, no tienes que cambiar nada.',
2),
('faq_car_03', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Puedo saber cuánto de cada corte me queda?',
'Sí. Cada venta descuenta el inventario en tiempo real. Puedes ver el stock de res, cerdo, pollo y cualquier otro corte desde el panel sin tener que ir al cuarto frío a contar. También recibes alertas cuando un corte baja del mínimo que tú definas.',
3),
('faq_car_04', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS es tu sistema de control de ventas e inventario — no reemplaza tu facturación SENIAT, la complementa. Usas ActivoPOS para el control diario de tu carnicería y tu sistema fiscal por separado para las obligaciones tributarias.',
4),
('faq_car_05', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Necesito instalar algo en mi carnicería?',
'No. ActivoPOS corre en el navegador — Chrome, Safari o cualquier browser moderno. Funciona desde el teléfono en el mostrador, desde una tablet en la caja, o desde una computadora en la trastienda. Sin instalación, sin técnico.',
5),
('faq_car_06', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Cómo se actualiza la tasa del dólar en mis precios?',
'Automáticamente. ActivoPOS consulta la tasa BCV varias veces al día. En cada cobro, el sistema muestra el precio en dólares y el equivalente en bolívares calculado en ese momento — sin que tú toques nada.',
6),
('faq_car_07', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Qué métodos de pago acepta ActivoPOS en mi carnicería?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia bancaria y USDT. En una carnicería donde el cliente paga rápido, un mismo cobro puede combinar varios métodos sin rehacer el ticket.',
7),
('faq_car_08', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Cuánto cuesta ActivoPOS para una carnicería?',
'El plan Mostrador arranca en $15/mes — cubre POS, inventario de cortes y cierre de caja para hasta 3 usuarios. El plan Negocio a $25/mes agrega catálogo digital y ventas por WhatsApp. El plan Pro a $40/mes es para carnicerías con mayor volumen y usuarios ilimitados.',
8),
('faq_car_09', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Puedo cancelar si no me convence?',
'Sí, en cualquier momento. No hay contrato anual ni penalización. Cancelas y tu carnicería sigue con acceso hasta el final del período que pagaste. Sin llamadas, sin trámites.',
9),
('faq_car_10', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Funciona desde el teléfono en el mostrador?',
'Sí. ActivoPOS está diseñado para funcionar desde el teléfono que ya tienes. El cajero de tu carnicería puede registrar ventas, ver precios y cobrar desde cualquier Android o iPhone sin necesidad de una caja registradora especial.',
10),
('faq_car_11', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Puedo tener varios cajeros con permisos diferentes?',
'Sí. Puedes crear usuarios con rol de cajero — solo ven el POS y la caja — o de administrador con acceso completo. Cada empleado de tu carnicería entra con su propio usuario. Sabes quién vendió qué y cuándo.',
11),
('faq_car_12', 'cmr9tor2a0003rcvxjtqaq5v4',
'¿Qué pasa si se va la luz o el internet en la carnicería?',
'Las ventas ya registradas quedan guardadas. Para nuevas ventas necesitas conexión — ActivoPOS es 100% en la nube. En una carnicería recomendamos tener el hotspot del teléfono como respaldo para los momentos de corte de servicio.',
12),

-- ============================================================
-- RESTAURANTE
-- ============================================================
('faq_res_01', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿ActivoPOS maneja mesas y comandas?',
'Sí. Puedes abrir una comanda por mesa, agregar platos durante el servicio y cerrar el ticket cuando el cliente pida la cuenta. La cocina recibe el pedido en tiempo real sin que el mesonero tenga que ir corriendo.',
1),
('faq_res_02', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Funciona con pantalla de cocina (KDS)?',
'Sí, en el plan Pro. El KDS muestra cada pedido en la cocina en el momento en que el mesonero lo registra — sin comandas en papel que se pierden o se mojan. Disponible en cualquier tablet o monitor que tengas en la cocina.',
2),
('faq_res_03', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Puedo tener varios mesoneros trabajando al mismo tiempo?',
'Sí. Cada mesonero entra con su propio usuario y maneja sus mesas. El sistema consolida todo en tiempo real — el administrador ve todas las mesas activas, los pedidos y lo que ha ingresado en el día desde una sola pantalla.',
3),
('faq_res_04', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS controla tus ventas, comandas e inventario de insumos — no reemplaza tu facturación SENIAT, la complementa. Tu restaurante usa ActivoPOS para la operación diaria y tu sistema fiscal para las obligaciones tributarias.',
4),
('faq_res_05', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Necesito instalar algo en mi restaurante?',
'No. ActivoPOS corre en el navegador de cualquier dispositivo. Los mesoneros usan su teléfono, la caja funciona desde una tablet, y la cocina ve los pedidos en cualquier monitor con internet. Sin instalación, sin técnico de sistemas.',
5),
('faq_res_06', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Cómo se actualiza la tasa del dólar en el menú?',
'Automáticamente. Tú defines los precios del menú en dólares una sola vez. En cada cobro, el sistema calcula el equivalente en bolívares con la tasa BCV del momento. Cuando el dólar sube, no tienes que actualizar nada manualmente.',
6),
('faq_res_07', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Qué métodos de pago acepta ActivoPOS en mi restaurante?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. Una mesa puede pagar con métodos mezclados en un solo ticket — sin anular la venta ni hacer malabares con la calculadora.',
7),
('faq_res_08', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Cuánto cuesta ActivoPOS para un restaurante?',
'El plan Negocio a $25/mes cubre comandas, inventario y catálogo digital para pedidos por WhatsApp. El plan Pro a $40/mes agrega KDS para la cocina, analytics avanzado y usuarios ilimitados — ideal para restaurantes con mayor movimiento.',
8),
('faq_res_09', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Puedo cancelar si no me convence?',
'Sí. No hay contrato anual ni permanencia mínima. Cancelas cuando quieras y tu restaurante mantiene el acceso hasta el final del período pagado. Sin formularios ni llamadas de retención.',
9),
('faq_res_10', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Los mesoneros pueden usar su teléfono para tomar pedidos?',
'Sí. ActivoPOS funciona desde cualquier teléfono Android o iPhone. El mesonero toma el pedido en la mesa desde su teléfono, la cocina lo ve al instante y el cajero cierra el ticket desde la caja — todo conectado sin hardware especial.',
10),
('faq_res_11', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Puedo ver el reporte de ventas por plato?',
'Sí. Los reportes muestran qué platos vendiste más, en qué horario, y cuál es tu margen real por producto. Sabes cuál es tu plato estrella y cuál no te está dejando ganancia — información para ajustar el menú con datos reales.',
11),
('faq_res_12', 'cmr9tor2t0007rcvxz6j0lhw8',
'¿Qué pasa si se va el internet durante el servicio?',
'Las ventas ya registradas quedan guardadas en el sistema. Para nuevas comandas necesitas conexión. Recomendamos tener el hotspot de un teléfono como respaldo — en un restaurante en hora pico, un corte de 5 minutos no puede paralizar la operación.',
12),

-- ============================================================
-- FERRETERÍAS
-- ============================================================
('faq_fer_01', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Puedo buscar productos por código o referencia?',
'Sí. La búsqueda del POS funciona por nombre, SKU y código de barras. En una ferretería con miles de referencias, escribes el código y el sistema lo encuentra en segundos — sin tener que memorizar ubicaciones ni revisar listas en papel.',
1),
('faq_fer_02', 'cmr9tor3b000brcvx7b7hkrk9',
'¿ActivoPOS maneja precios al mayor y al detal?',
'Sí. Puedes configurar listas de precio por tipo de cliente. Los contratistas y constructores que te compran al mayor ven sus precios, y los clientes de mostrador ven los suyos. El cajero selecciona el tipo de cliente y el sistema aplica la lista correcta.',
2),
('faq_fer_03', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Puedo actualizar precios masivamente cuando sube el dólar?',
'Sí. Puedes actualizar precios por categoría o aplicar un porcentaje de ajuste a todo el inventario desde el panel de administración. En una ferretería donde el dólar mueve todo el catálogo, eso te ahorra horas de trabajo manual.',
3),
('faq_fer_04', 'cmr9tor3b000brcvx7b7hkrk9',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS controla tu inventario, ventas y caja — no reemplaza tu facturación SENIAT, la complementa. Tu ferretería usa ActivoPOS para el control operativo diario y tu sistema fiscal para el cumplimiento tributario.',
4),
('faq_fer_05', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Necesito instalar algo en mi ferretería?',
'No. ActivoPOS corre en el navegador de cualquier dispositivo. La caja funciona desde una computadora, una tablet o el teléfono del cajero. Sin instalación, sin licencias por equipo, sin técnico de sistemas cada vez que se actualiza.',
5),
('faq_fer_06', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Cómo se actualiza la tasa del dólar en mis precios?',
'Automáticamente. ActivoPOS consulta la tasa BCV varias veces al día. Los precios de tu ferretería en bolívares se recalculan solos en cada cobro — tú defines el precio en dólares una sola vez y el sistema hace el resto.',
6),
('faq_fer_07', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Qué métodos de pago acepta ActivoPOS en mi ferretería?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. Para ventas al mayor donde el contratista paga en partes, puedes registrar pagos mixtos en un solo ticket.',
7),
('faq_fer_08', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Cuánto cuesta ActivoPOS para una ferretería?',
'El plan Negocio a $25/mes es el más usado en ferreterías — cubre hasta 500 productos, hasta 10 usuarios, catálogo digital y ventas por WhatsApp. El plan Pro a $40/mes es para ferreterías con catálogo masivo y usuarios ilimitados.',
8),
('faq_fer_09', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Puedo cancelar si no me convence?',
'Sí, en cualquier momento. No hay contrato anual ni cláusula de permanencia. Tu ferretería mantiene el acceso hasta el final del período pagado y listo — sin llamadas de retención.',
9),
('faq_fer_10', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Funciona desde el teléfono en el mostrador?',
'Sí. El cajero de tu ferretería puede registrar ventas desde cualquier teléfono Android o iPhone. Si tienes una computadora en la caja, también funciona. No necesitas hardware especial ni caja registradora dedicada.',
10),
('faq_fer_11', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Puedo saber qué productos se están agotando?',
'Sí. ActivoPOS te alerta cuando cualquier producto baja del stock mínimo que tú definas. En una ferretería con miles de referencias, eso significa que nunca te quedas sin cemento, cabilla o pintura en temporada alta sin saberlo.',
11),
('faq_fer_12', 'cmr9tor3b000brcvx7b7hkrk9',
'¿Qué pasa si se va el internet en la ferretería?',
'Las ventas ya registradas quedan guardadas. Para nuevas ventas necesitas conexión. Recomendamos tener el hotspot del teléfono como respaldo — en hora pico, un corte de internet no puede parar la caja de tu ferretería.',
12),

-- ============================================================
-- FARMACIAS
-- ============================================================
('faq_far_01', 'cmr9tor3s000frcvxz4vivpgp',
'¿ActivoPOS maneja fechas de vencimiento de medicamentos?',
'Sí. Puedes registrar la fecha de vencimiento de cada lote al ingresar el inventario. El sistema te alerta cuando un medicamento está próximo a vencer para que lo retires o lo muevas antes de que sea una pérdida.',
1),
('faq_far_02', 'cmr9tor3s000frcvxz4vivpgp',
'¿Cómo manejo los precios regulados en mi farmacia?',
'Puedes mantener dos precios por producto: el precio regulado oficial y el precio libre. El cajero selecciona cuál aplica en cada venta. El sistema registra ambos y los reportes te muestran exactamente cuánto vendiste a precio regulado y cuánto a precio libre.',
2),
('faq_far_03', 'cmr9tor3s000frcvxz4vivpgp',
'¿Puedo cobrar con Pago Móvil y efectivo en el mismo ticket?',
'Sí. En una farmacia donde el cliente paga una parte en Pago Móvil y completa en efectivo, ActivoPOS registra el pago mixto en un solo ticket sin necesidad de anular o hacer dos transacciones separadas.',
3),
('faq_far_04', 'cmr9tor3s000frcvxz4vivpgp',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS es tu sistema de control de ventas e inventario — no reemplaza tu facturación SENIAT, la complementa. Tu farmacia usa ActivoPOS para el control diario y tu sistema fiscal para las obligaciones tributarias.',
4),
('faq_far_05', 'cmr9tor3s000frcvxz4vivpgp',
'¿Necesito instalar algo en mi farmacia?',
'No. ActivoPOS corre en el navegador de cualquier dispositivo. El cajero trabaja desde la computadora de la farmacia, desde una tablet en el mostrador, o desde su teléfono si es necesario. Sin instalación, sin técnico.',
5),
('faq_far_06', 'cmr9tor3s000frcvxz4vivpgp',
'¿Cómo se actualiza la tasa del dólar para los medicamentos importados?',
'Automáticamente. ActivoPOS consulta la tasa BCV varias veces al día. Para los medicamentos con precio en dólares, el equivalente en bolívares se recalcula solo en cada cobro. Para los de precio regulado en bolívares, el precio no cambia hasta que tú lo actualices.',
6),
('faq_far_07', 'cmr9tor3s000frcvxz4vivpgp',
'¿Qué métodos de pago acepta ActivoPOS en mi farmacia?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. Para farmacias con clientes frecuentes que mezclan métodos de pago en cada visita, el sistema los registra todos en un solo ticket.',
7),
('faq_far_08', 'cmr9tor3s000frcvxz4vivpgp',
'¿Cuánto cuesta ActivoPOS para una farmacia?',
'El plan Mostrador a $15/mes es suficiente para farmacias pequeñas con hasta 100 productos y 3 usuarios. El plan Negocio a $25/mes agrega catálogo digital y ventas por WhatsApp. El plan Pro a $40/mes es para farmacias con catálogo completo y personal amplio.',
8),
('faq_far_09', 'cmr9tor3s000frcvxz4vivpgp',
'¿Puedo cancelar si no me convence?',
'Sí. No hay contrato anual ni penalización por cancelar. Tu farmacia mantiene el acceso hasta el final del período pagado. Sin llamadas ni trámites complicados.',
9),
('faq_far_10', 'cmr9tor3s000frcvxz4vivpgp',
'¿Funciona desde el teléfono en el mostrador?',
'Sí. El cajero de tu farmacia puede registrar ventas desde cualquier teléfono Android o iPhone. Ideal para farmacias donde el espacio en el mostrador es limitado y no cabe una computadora de escritorio.',
10),
('faq_far_11', 'cmr9tor3s000frcvxz4vivpgp',
'¿Puedo saber qué medicamentos se están agotando?',
'Sí. ActivoPOS te alerta cuando cualquier producto baja del stock mínimo que definas. En una farmacia, nunca más te quedas sin el medicamento que más rotan tus clientes sin saberlo con anticipación.',
11),
('faq_far_12', 'cmr9tor3s000frcvxz4vivpgp',
'¿Qué pasa si se va el internet en la farmacia?',
'Las ventas ya registradas quedan guardadas. Para nuevas ventas necesitas conexión. Recomendamos el hotspot del teléfono como respaldo — en una farmacia, no puede haber momentos sin poder registrar una venta.',
12),

-- ============================================================
-- TIENDAS DE ROPA
-- ============================================================
('faq_ropa_01', 'cmr9tor6v000jrcvxw875298h',
'¿ActivoPOS maneja tallas, colores y variantes de ropa?',
'Sí. Cada prenda se configura con sus variantes — talla S, M, L, XL, colores disponibles — y el sistema lleva el inventario por variante. Sabes exactamente cuántas unidades tienes de cada combinación sin ir al depósito a revisar.',
1),
('faq_ropa_02', 'cmr9tor6v000jrcvxw875298h',
'¿Puedo mostrar el catálogo a clientes que preguntan por WhatsApp?',
'Sí. Con el catálogo digital de ActivoPOS, tus clientes pueden ver las prendas disponibles con fotos, tallas y precios actualizados desde un link. Hacen su pedido por WhatsApp con el detalle exacto — sin que tú tengas que ir a buscar si hay stock.',
2),
('faq_ropa_03', 'cmr9tor6v000jrcvxw875298h',
'¿Puedo manejar apartados y ventas a crédito?',
'Sí. ActivoPOS registra ventas a crédito con el cliente asignado y lleva el saldo pendiente. Para los apartados, registras el adelanto y el sistema te muestra cuánto queda por cobrar antes de entregar la prenda.',
3),
('faq_ropa_04', 'cmr9tor6v000jrcvxw875298h',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS es tu sistema de control de ventas e inventario — no reemplaza tu facturación SENIAT, la complementa. Tu tienda de ropa usa ActivoPOS para el control diario y tu sistema fiscal para las obligaciones tributarias.',
4),
('faq_ropa_05', 'cmr9tor6v000jrcvxw875298h',
'¿Necesito instalar algo en mi tienda?',
'No. ActivoPOS corre en el navegador de cualquier dispositivo. La cajera trabaja desde el teléfono, desde una tablet en el mostrador o desde la computadora del local. Sin instalación, sin actualizaciones manuales.',
5),
('faq_ropa_06', 'cmr9tor6v000jrcvxw875298h',
'¿Cómo se actualiza la tasa del dólar en los precios de la ropa?',
'Automáticamente. Defines el precio de cada prenda en dólares una sola vez. En cada cobro, el sistema muestra el equivalente en bolívares calculado con la tasa BCV del momento — sin que tengas que recalcular ni cambiar etiquetas.',
6),
('faq_ropa_07', 'cmr9tor6v000jrcvxw875298h',
'¿Qué métodos de pago acepta ActivoPOS en mi tienda de ropa?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. Una clienta puede pagar su apartado en Pago Móvil y completar en efectivo — el sistema lo registra todo en un solo movimiento.',
7),
('faq_ropa_08', 'cmr9tor6v000jrcvxw875298h',
'¿Cuánto cuesta ActivoPOS para una tienda de ropa?',
'El plan Negocio a $25/mes es el más usado en tiendas de ropa — incluye catálogo digital para vender por WhatsApp, inventario por variante y hasta 10 usuarios. El plan Pro a $40/mes agrega analytics y usuarios ilimitados para tiendas con mayor equipo.',
8),
('faq_ropa_09', 'cmr9tor6v000jrcvxw875298h',
'¿Puedo cancelar si no me convence?',
'Sí, en cualquier momento. Sin contrato anual ni penalización. Tu tienda mantiene el acceso hasta el final del período pagado y listo.',
9),
('faq_ropa_10', 'cmr9tor6v000jrcvxw875298h',
'¿La cajera puede usar el teléfono para registrar ventas?',
'Sí. ActivoPOS está diseñado mobile-first. La cajera registra ventas, revisa inventario por talla y cobra desde cualquier teléfono Android o iPhone — sin necesidad de una caja registradora ni computadora especial.',
10),
('faq_ropa_11', 'cmr9tor6v000jrcvxw875298h',
'¿Puedo saber qué tallas y colores se venden más?',
'Sí. Los reportes muestran los productos más vendidos por período, incluyendo las variantes. Sabes qué talla rota más, qué color no se mueve, y cuándo reponer antes de quedarte sin el más pedido.',
11),
('faq_ropa_12', 'cmr9tor6v000jrcvxw875298h',
'¿Qué pasa si se va el internet en la tienda?',
'Las ventas ya registradas quedan guardadas. Para nuevas ventas necesitas conexión. Recomendamos tener el hotspot del teléfono como respaldo para no parar las ventas en ningún momento.',
12),

-- ============================================================
-- ABASTOS / BODEGAS
-- ============================================================
('faq_abs_01', 'cmr9tor78000nrcvx4nvtcglc',
'¿Puedo controlar los fiaditos y ventas a crédito en la bodega?',
'Sí. ActivoPOS registra las ventas a crédito con el cliente asignado y lleva el saldo pendiente de cada uno. Se acabó la libreta de fiaditos — sabes exactamente quién te debe, cuánto y desde cuándo.',
1),
('faq_abs_02', 'cmr9tor78000nrcvx4nvtcglc',
'¿ActivoPOS me avisa cuando se está acabando un producto?',
'Sí. Defines el stock mínimo de cada producto y el sistema te alerta cuando baja de ese nivel. En una bodega donde vender de todo, nunca más te quedas sin harina, aceite o azúcar sin saberlo con tiempo de reponer.',
2),
('faq_abs_03', 'cmr9tor78000nrcvx4nvtcglc',
'¿Puedo saber cuánto entró al final del día sin contar a mano?',
'Sí. El cierre de caja de ActivoPOS te muestra exactamente cuánto vendiste, en qué método de pago y cuánto debería haber en caja — sin sumar recibos ni cuadrar a mano. Sabes si cuadra o si hay diferencia en segundos.',
3),
('faq_abs_04', 'cmr9tor78000nrcvx4nvtcglc',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS es tu sistema de control de ventas e inventario — no reemplaza tu facturación SENIAT, la complementa. Tu abasto usa ActivoPOS para el control diario y tu sistema fiscal para las obligaciones tributarias.',
4),
('faq_abs_05', 'cmr9tor78000nrcvx4nvtcglc',
'¿Necesito instalar algo en la bodega?',
'No. ActivoPOS corre en el navegador. Funciona desde el teléfono en el mostrador, desde una tablet en la caja o desde una computadora. Sin instalación, sin técnico de sistemas, sin actualizaciones manuales.',
5),
('faq_abs_06', 'cmr9tor78000nrcvx4nvtcglc',
'¿Cómo se actualiza la tasa del dólar en los precios de la bodega?',
'Automáticamente. Defines los precios en dólares una sola vez y el sistema calcula el equivalente en bolívares en cada cobro con la tasa BCV del momento. Cuando sube el dólar, no tienes que cambiar nada en la bodega.',
6),
('faq_abs_07', 'cmr9tor78000nrcvx4nvtcglc',
'¿Qué métodos de pago acepta ActivoPOS en la bodega?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. En una bodega donde el cliente a veces paga en dos partes, el sistema registra el pago mixto en un solo ticket.',
7),
('faq_abs_08', 'cmr9tor78000nrcvx4nvtcglc',
'¿Cuánto cuesta ActivoPOS para una bodega o abasto?',
'El plan Mostrador a $15/mes es suficiente para bodegas pequeñas — cubre POS, inventario y cierre de caja para hasta 3 usuarios y 100 productos. El plan Negocio a $25/mes agrega catálogo digital y más capacidad para abastos con mayor surtido.',
8),
('faq_abs_09', 'cmr9tor78000nrcvx4nvtcglc',
'¿Puedo cancelar si no me convence?',
'Sí. No hay contrato anual ni penalización. Tu bodega mantiene el acceso hasta el final del período pagado y puedes cancelar cuando quieras sin trámites.',
9),
('faq_abs_10', 'cmr9tor78000nrcvx4nvtcglc',
'¿Funciona desde el teléfono en el mostrador de la bodega?',
'Sí. El cajero registra ventas desde cualquier teléfono Android o iPhone. Perfecto para bodegas donde no hay espacio para una computadora en el mostrador — el teléfono se convierte en la caja registradora.',
10),
('faq_abs_11', 'cmr9tor78000nrcvx4nvtcglc',
'¿Puedo ver qué productos se venden más en mi bodega?',
'Sí. Los reportes muestran los productos más vendidos por día, semana o mes. Sabes qué rotan más, qué está quieto y cuándo necesitas reponer para no perder ventas en los productos estrella de tu bodega.',
11),
('faq_abs_12', 'cmr9tor78000nrcvx4nvtcglc',
'¿Qué pasa si se va la luz o el internet en la bodega?',
'Las ventas ya registradas quedan guardadas. Para nuevas ventas necesitas conexión. En una bodega recomendamos el hotspot del teléfono como respaldo — los clientes no esperan y la venta no puede parar.',
12),

-- ============================================================
-- TECNOLOGÍA / ELECTRÓNICOS
-- ============================================================
('faq_tec_01', 'cmr9tor7s000rrcvxk633xs8c',
'¿ActivoPOS lleva control de seriales y garantías?',
'Sí. Puedes registrar el serial de cada equipo vendido y asignarlo al cliente. Cuando alguien llega con un reclamo de garantía, buscas el serial y sabes exactamente a quién le vendiste, cuándo y a qué precio — sin revisar facturas en papel.',
1),
('faq_tec_02', 'cmr9tor7s000rrcvxk633xs8c',
'¿Puedo manejar órdenes de reparación y servicio técnico?',
'Sí. En ActivoPOS puedes registrar una orden de servicio con el equipo, el problema reportado, el costo de la reparación y el estado. El cliente puede consultar si su equipo está listo y tú tienes el historial de cada reparación registrado.',
2),
('faq_tec_03', 'cmr9tor7s000rrcvxk633xs8c',
'¿Cómo manejo los precios de equipos que cambian con el dólar?',
'Define el precio de cada equipo en dólares una sola vez. ActivoPOS calcula el equivalente en bolívares automáticamente con la tasa BCV del momento de la venta. Cuando el dólar sube, no tienes que actualizar nada — el precio en bolívares se ajusta solo.',
3),
('faq_tec_04', 'cmr9tor7s000rrcvxk633xs8c',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS controla tus ventas, inventario de equipos y órdenes de servicio — no reemplaza tu facturación SENIAT, la complementa. Tu tienda de tecnología usa ActivoPOS para la operación y tu sistema fiscal para las obligaciones tributarias.',
4),
('faq_tec_05', 'cmr9tor7s000rrcvxk633xs8c',
'¿Necesito instalar algo en mi tienda de tecnología?',
'No. ActivoPOS corre en el navegador de cualquier dispositivo. Funciona desde la computadora del mostrador, desde una tablet en la vitrina o desde el teléfono del técnico. Sin instalación, sin licencias adicionales por equipo.',
5),
('faq_tec_06', 'cmr9tor7s000rrcvxk633xs8c',
'¿Cómo se actualiza la tasa del dólar en los precios de equipos?',
'Automáticamente. ActivoPOS consulta la tasa BCV varias veces al día. Los precios en bolívares de todos tus equipos y accesorios se recalculan solos en cada cobro — sin que tengas que tocar el catálogo cada vez que el dólar se mueve.',
6),
('faq_tec_07', 'cmr9tor7s000rrcvxk633xs8c',
'¿Qué métodos de pago acepta ActivoPOS en mi tienda de tecnología?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. Para ventas de equipos de alto valor donde el cliente paga en partes, el sistema registra el pago mixto en un solo ticket.',
7),
('faq_tec_08', 'cmr9tor7s000rrcvxk633xs8c',
'¿Cuánto cuesta ActivoPOS para una tienda de tecnología?',
'El plan Negocio a $25/mes cubre ventas, inventario de equipos, catálogo digital y hasta 10 usuarios. El plan Pro a $40/mes agrega analytics avanzado y usuarios ilimitados — ideal para tiendas con taller de reparación y equipo de ventas.',
8),
('faq_tec_09', 'cmr9tor7s000rrcvxk633xs8c',
'¿Puedo cancelar si no me convence?',
'Sí. Sin contrato anual ni penalización. Tu tienda mantiene el acceso hasta el final del período pagado. Cancelas cuando quieras sin llamadas de retención.',
9),
('faq_tec_10', 'cmr9tor7s000rrcvxk633xs8c',
'¿Funciona desde el teléfono en el mostrador?',
'Sí. El vendedor puede registrar ventas y consultar inventario desde cualquier teléfono Android o iPhone. El técnico puede actualizar el estado de una reparación desde su teléfono sin ir a la computadora del mostrador.',
10),
('faq_tec_11', 'cmr9tor7s000rrcvxk633xs8c',
'¿Puedo ver qué equipos y accesorios se venden más?',
'Sí. Los reportes muestran los productos más vendidos, tu margen real por equipo y cuáles están sin movimiento. Información para decidir qué reponer, qué liquidar y cuáles son los accesorios que más te dejan.',
11),
('faq_tec_12', 'cmr9tor7s000rrcvxk633xs8c',
'¿Qué pasa si se va el internet en la tienda?',
'Las ventas ya registradas quedan guardadas. Para nuevas ventas y órdenes de servicio necesitas conexión. Recomendamos el hotspot del teléfono como respaldo — en una tienda de tecnología, no tener internet no puede parar las ventas.',
12),

-- ============================================================
-- REPUESTOS
-- ============================================================
('faq_rep_01', 'cmr9tor86000vrcvxcznm1opt',
'¿Puedo buscar repuestos por código o referencia del fabricante?',
'Sí. La búsqueda del POS funciona por nombre, SKU y código de barras. En una repuestera con miles de referencias, escribes el código o el nombre de la pieza y el sistema la encuentra en segundos — sin buscar en catálogos físicos ni libretas.',
1),
('faq_rep_02', 'cmr9tor86000vrcvxcznm1opt',
'¿ActivoPOS maneja precios al mayor y al detal para talleres?',
'Sí. Puedes configurar listas de precio por tipo de cliente. Los talleres mecánicos que te compran al mayor tienen su precio, y los clientes de mostrador tienen el suyo. El cajero selecciona el tipo de cliente y el sistema aplica la lista correcta automáticamente.',
2),
('faq_rep_03', 'cmr9tor86000vrcvxcznm1opt',
'¿Puedo ver qué referencias se mueven y cuáles llevan meses sin venderse?',
'Sí. Los reportes de ActivoPOS muestran los productos más vendidos y los que no tienen movimiento por período. En una repuestera, eso significa saber qué repuestos reponer y cuáles liquidar antes de que se conviertan en inventario muerto.',
3),
('faq_rep_04', 'cmr9tor86000vrcvxcznm1opt',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS controla tu inventario de repuestos, ventas y caja — no reemplaza tu facturación SENIAT, la complementa. Tu repuestera usa ActivoPOS para el control operativo y tu sistema fiscal para las obligaciones tributarias.',
4),
('faq_rep_05', 'cmr9tor86000vrcvxcznm1opt',
'¿Necesito instalar algo en mi repuestera?',
'No. ActivoPOS corre en el navegador de cualquier dispositivo. La caja funciona desde una computadora, una tablet o el teléfono del cajero. Sin instalación, sin técnico de sistemas, sin actualizaciones manuales.',
5),
('faq_rep_06', 'cmr9tor86000vrcvxcznm1opt',
'¿Cómo se actualiza la tasa del dólar en los precios de repuestos?',
'Automáticamente. Defines el precio de cada repuesto en dólares una sola vez. En cada venta, el sistema calcula el equivalente en bolívares con la tasa BCV del momento — sin que tengas que recalcular ni actualizar precios cuando el dólar sube.',
6),
('faq_rep_07', 'cmr9tor86000vrcvxcznm1opt',
'¿Qué métodos de pago acepta ActivoPOS en mi repuestera?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. Para talleres que pagan en partes o mezclan métodos, el sistema registra el pago mixto en un solo ticket sin complicaciones.',
7),
('faq_rep_08', 'cmr9tor86000vrcvxcznm1opt',
'¿Cuánto cuesta ActivoPOS para una repuestera?',
'El plan Negocio a $25/mes es el más usado en repuesteras — cubre hasta 500 referencias, hasta 10 usuarios, catálogo digital y ventas por WhatsApp para talleres. El plan Pro a $40/mes es para repuesteras con catálogo masivo y usuarios ilimitados.',
8),
('faq_rep_09', 'cmr9tor86000vrcvxcznm1opt',
'¿Puedo cancelar si no me convence?',
'Sí. Sin contrato anual ni penalización. Tu repuestera mantiene el acceso hasta el final del período pagado y cancelas cuando quieras.',
9),
('faq_rep_10', 'cmr9tor86000vrcvxcznm1opt',
'¿Funciona desde el teléfono en el mostrador?',
'Sí. El cajero registra ventas y busca referencias desde cualquier teléfono Android o iPhone. En una repuestera donde el mostrador es el centro de todo, no necesitas una computadora especial para tener el sistema corriendo.',
10),
('faq_rep_11', 'cmr9tor86000vrcvxcznm1opt',
'¿Puedo saber qué repuestos se están agotando?',
'Sí. ActivoPOS te alerta cuando cualquier referencia baja del stock mínimo que definas. En una repuestera con miles de referencias, eso significa que nunca te quedas sin las piezas que más rotan sin saberlo con anticipación.',
11),
('faq_rep_12', 'cmr9tor86000vrcvxcznm1opt',
'¿Qué pasa si se va el internet en la repuestera?',
'Las ventas ya registradas quedan guardadas. Para nuevas ventas necesitas conexión. Recomendamos el hotspot del teléfono como respaldo — en una repuestera en hora pico, un corte no puede parar la caja.',
12),

-- ============================================================
-- SERVICIOS Y OFICINA
-- ============================================================
('faq_ser_01', 'cmr9tor8q0013rcvx66mexwzw',
'¿ActivoPOS maneja cotizaciones para servicios profesionales?',
'Sí. Puedes crear cotizaciones con el detalle de cada servicio, enviárselas al cliente en PDF y registrar cuáles se aprobaron. Se acabó hacer cotizaciones en Word sin saber en qué quedaron — tienes el historial completo de cada propuesta.',
1),
('faq_ser_02', 'cmr9tor8q0013rcvx66mexwzw',
'¿Cómo llevo el control de clientes que me deben?',
'Con el módulo de cuentas por cobrar de ActivoPOS. Registras cada servicio prestado, el pago recibido y el saldo pendiente por cliente. Sabes exactamente quién te debe, cuánto y desde cuándo — sin libreta ni Excel.',
2),
('faq_ser_03', 'cmr9tor8q0013rcvx66mexwzw',
'¿Puedo saber cuánto facturé y cuál es mi rentabilidad real al mes?',
'Sí. Los reportes financieros de ActivoPOS muestran tus ingresos por período, el detalle por tipo de servicio y tu utilidad real. Al cierre del mes sabes exactamente cuánto entraste, cuánto gastaste y cuánto te quedó — sin esperar al contador.',
3),
('faq_ser_04', 'cmr9tor8q0013rcvx66mexwzw',
'¿ActivoPOS reemplaza mi facturación del SENIAT?',
'No. ActivoPOS es tu sistema de control de cobros y clientes — no reemplaza tu facturación SENIAT, la complementa. Tu empresa de servicios usa ActivoPOS para el control operativo y tu sistema fiscal para las obligaciones tributarias.',
4),
('faq_ser_05', 'cmr9tor8q0013rcvx66mexwzw',
'¿Necesito instalar algo en mi oficina?',
'No. ActivoPOS corre en el navegador de cualquier dispositivo. Funciona desde la computadora de la oficina, desde la tablet en reuniones con clientes, o desde el teléfono cuando estás en campo. Sin instalación, sin técnico.',
5),
('faq_ser_06', 'cmr9tor8q0013rcvx66mexwzw',
'¿Cómo se actualiza la tasa del dólar en mis tarifas de servicios?',
'Defines tus tarifas en dólares una sola vez. En cada cobro, ActivoPOS calcula el equivalente en bolívares con la tasa BCV del momento — sin que tengas que recalcular ni actualizar tus tarifas cada vez que el dólar se mueve.',
6),
('faq_ser_07', 'cmr9tor8q0013rcvx66mexwzw',
'¿Qué métodos de pago acepta ActivoPOS para cobros de servicios?',
'Todos los que usa Venezuela: Pago Móvil, Zelle, efectivo en dólares, efectivo en bolívares, transferencia y USDT. Para clientes que pagan en cuotas o abonan al servicio, el sistema registra cada pago contra la factura correspondiente.',
7),
('faq_ser_08', 'cmr9tor8q0013rcvx66mexwzw',
'¿Cuánto cuesta ActivoPOS para una empresa de servicios?',
'El plan Negocio a $25/mes cubre cotizaciones, cobros, cuentas por cobrar y hasta 10 usuarios. El plan Pro a $40/mes agrega analytics avanzado y usuarios ilimitados — ideal para consultoras y gestorías con equipo de campo y oficina.',
8),
('faq_ser_09', 'cmr9tor8q0013rcvx66mexwzw',
'¿Puedo cancelar si no me convence?',
'Sí. Sin contrato anual ni penalización. Tu empresa mantiene el acceso hasta el final del período pagado y cancelas cuando quieras sin trámites.',
9),
('faq_ser_10', 'cmr9tor8q0013rcvx66mexwzw',
'¿Funciona desde el teléfono cuando estoy fuera de la oficina?',
'Sí. ActivoPOS funciona desde cualquier teléfono Android o iPhone. Puedes registrar un cobro, revisar cuentas por cobrar o consultar el estado de una cotización desde donde estés — sin necesidad de estar en la oficina.',
10),
('faq_ser_11', 'cmr9tor8q0013rcvx66mexwzw',
'¿Puedo ver qué servicios me generan más ingresos?',
'Sí. Los reportes muestran tus servicios más vendidos, el ingreso por tipo de servicio y tu margen real. Información para decidir en qué especializarte más, qué servicios subir de precio y cuáles no te están dejando suficiente.',
11),
('faq_ser_12', 'cmr9tor8q0013rcvx66mexwzw',
'¿Qué pasa si se va el internet estando con un cliente?',
'Las operaciones ya registradas quedan guardadas. Para nuevas transacciones necesitas conexión. Con el hotspot del teléfono como respaldo, nunca te quedas sin poder registrar un cobro en medio de una reunión con un cliente.',
12);
