'use client'

import { useEffect, useRef, useState } from 'react'
import { ArrowRight, Check, X, Loader2 } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import type { OnboardingState } from '../types'
import styles from '../registro.module.css'

interface StepProps {
  data:   OnboardingState
  update: (patch: Partial<OnboardingState>) => void
  onNext: () => void
}

function slugify(text: string): string {
  return text
    .toLowerCase()
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 50)
}

async function checkSlug(slug: string): Promise<boolean> {
  const res = await fetch(`/api/onboarding/check-slug?slug=${encodeURIComponent(slug)}`)
  if (!res.ok) return false
  const json = await res.json() as { available: boolean }
  return json.available
}

export default function Step3Slug({ data, update, onNext }: StepProps) {
  const [checking, setChecking]       = useState(false)
  const [available, setAvailable]     = useState<boolean | null>(null)
  const [suggestions, setSuggestions] = useState<string[]>([])
  const autoGenerated = useRef(false)

  // Auto-generar slug del nombre del negocio al entrar al paso
  useEffect(() => {
    if (!autoGenerated.current && !data.slug && data.businessName) {
      update({ slug: slugify(data.businessName) })
      autoGenerated.current = true
    }
  }, [data.businessName, data.slug, update])

  // Verificación en tiempo real (debounce 500ms)
  useEffect(() => {
    const slug = data.slug
    if (!slug || slug.length < 3) {
      setAvailable(null)
      setSuggestions([])
      return
    }

    setChecking(true)
    const timer = setTimeout(async () => {
      const isAvailable = await checkSlug(slug)
      setAvailable(isAvailable)
      setChecking(false)

      if (!isAvailable) {
        const candidates = [`${slug}-1`, `${slug}-store`, `${slug}-${Math.floor(Math.random() * 900 + 100)}`]
        const results = await Promise.all(candidates.map(async c => ({ c, ok: await checkSlug(c) })))
        setSuggestions(results.filter(r => r.ok).map(r => r.c))
      } else {
        setSuggestions([])
      }
    }, 500)

    return () => clearTimeout(timer)
  }, [data.slug])

  const isValid = available === true

  return (
    <>
      <h1 className={styles.stepTitle}>Tu URL</h1>
      <p className={styles.stepSubtitle}>La dirección web de tu catálogo</p>

      <div className={styles.formField}>
        <label className={styles.fieldLabel}>URL del catálogo</label>
        <div className={styles.slugInputRow}>
          <span className={styles.slugPrefix}>activopos.com/catalogo/</span>
          <input
            className={styles.slugInput}
            value={data.slug}
            onChange={e => update({ slug: slugify(e.target.value) })}
            aria-label="Slug del catálogo"
          />
        </div>

        <div className={styles.slugStatus}>
          {checking && <><Loader2 size={13} aria-hidden="true" /> Verificando…</>}
          {!checking && available === true && (
            <span className={styles.slugAvailable}><Check size={13} aria-hidden="true" /> Disponible</span>
          )}
          {!checking && available === false && (
            <span className={styles.slugTaken}><X size={13} aria-hidden="true" /> No disponible</span>
          )}
        </div>

        {suggestions.length > 0 && (
          <div className={styles.slugSuggestions}>
            {suggestions.map(s => (
              <button key={s} type="button" className={styles.slugChip} onClick={() => update({ slug: s })}>
                {s}
              </button>
            ))}
          </div>
        )}
      </div>

      <Button fullWidth size="lg" rightIcon={<ArrowRight size={16} />} disabled={!isValid} onClick={onNext}>
        Crear Mi Tienda
      </Button>
    </>
  )
}
